#!/usr/bin/python2.7
__author__ = 'chris'
import sys

sys.path.append('hooks')

from charmhelpers.contrib.storage.linux.ceph import remove_erasure_profile
from charmhelpers.core.hookenv import action_get, log


def delete_erasure_profile():
    name = action_get("name")

    remove_erasure_profile(service='admin', profile_name=name)


if __name__ == '__main__':
    delete_erasure_profile()
